<script setup lang="ts">
import FirstTouchPanel from '../components/FirstTouchPanel.vue';

</script>

<template>
  <div style="max-width:800px;margin:0 auto">
    <h1>Terms of Service</h1>
    <p style="font-size:0.85rem;opacity:0.6">Last updated: April 2026 | To be reviewed by legal counsel before commercial launch</p>

    <h2>1. Nature of Service</h2>
    <p>Divinr AI ("the Platform") provides AI-generated market analysis, signals, and educational tools. The Platform uses artificial intelligence models to analyze financial data, news articles, and market indicators to generate analytical perspectives from multiple AI analyst personas.</p>

    <h2>2. Not Investment Advice</h2>
    <p><strong>The information, analysis, and signals provided by Divinr AI are for educational and informational purposes only and do not constitute investment advice, financial advice, trading advice, or any other sort of advice.</strong> You should not treat any of the Platform's content as such.</p>
    <p>The Platform does not take into account your personal financial situation, investment objectives, risk tolerance, or specific needs. Any trading decisions you make are solely your responsibility.</p>

    <h2>3. No Fiduciary Relationship</h2>
    <p>Use of this Platform does not create an advisory, fiduciary, or professional services relationship between you and Divinr AI, its operators, or its affiliates. The Platform is a technology tool, not a financial advisor.</p>

    <h2>4. AI-Generated Content</h2>
    <p>All analysis on this Platform is generated by artificial intelligence models. AI-generated content may contain errors, inaccuracies, outdated information, or hallucinations. The AI analysts are personas — they are not real people, and their "opinions" are algorithmically generated based on data inputs.</p>
    <p>You should always verify information from independent sources and conduct your own research before making any investment decisions.</p>

    <h2>5. Past Performance</h2>
    <p>Past performance of AI analysts, predictions, or the Platform as a whole does not guarantee future results. Historical accuracy rates, portfolio returns, and analyst track records are provided for informational purposes only and should not be interpreted as indicators of future performance.</p>

    <h2>6. Risk Disclosure</h2>
    <p>Investing in financial markets involves substantial risk, including the potential loss of your entire investment. You should be aware that:</p>
    <ul>
      <li>Stock prices can be volatile and may decline significantly</li>
      <li>Past performance is not indicative of future results</li>
      <li>AI-generated analysis may be incorrect</li>
      <li>Market conditions can change rapidly and unpredictably</li>
      <li>You may lose some or all of the money you invest</li>
    </ul>

    <h2>7. Paper Trading</h2>
    <p>Portfolio tracking on this Platform uses simulated ("paper") trading only. No real securities are bought or sold through the Platform. Simulated results may differ significantly from actual trading due to factors including but not limited to: execution timing, slippage, commissions, market impact, and liquidity constraints.</p>

    <h2>8. Limitation of Liability</h2>
    <p>To the maximum extent permitted by applicable law, Divinr AI and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages arising from or related to your use of the Platform, including but not limited to damages for loss of profits, data, or other intangible losses, regardless of whether such damages are based on warranty, contract, tort, or any other legal theory.</p>

    <h2>9. Data Sources</h2>
    <p>The Platform aggregates data from third-party sources including but not limited to news feeds, financial data APIs, and public filings. Divinr AI does not guarantee the accuracy, completeness, or timeliness of third-party data. Data source availability may change without notice.</p>

    <h2>10. Changes to Terms</h2>
    <p>We reserve the right to modify these Terms of Service at any time. Continued use of the Platform after changes constitutes acceptance of the modified terms.</p>

    <h2>11. Contact</h2>
    <p>For questions about these Terms of Service, contact: legal@divinr.ai</p>
  
  <FirstTouchPanel surface-key="settings.terms" />
  </div>
</template>

<style scoped>
h1 { margin-bottom: 8px; }
h2 { margin-top: 24px; font-size: 1.1rem; }
p, li { font-size: 0.9rem; line-height: 1.6; color: #444; }
ul { padding-left: 20px; }
</style>
